# 项目相关配置
home-service:
  # 名称
  name: home-service
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/home_service/uploadPath，Linux配置 /home/home_service/uploadPath）
  profile: ~/home_service/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

security:
  auth-login-url: "/openApi/login"
  jwt-secret-key: "p2s5v8y/B?E(H+MbQeThVmYq3t6w9z$C&F)J@NcRfUjXnZr4u7x!A%D*G-KaPdS"
  token-prefix: "Bearer "
  token-header: "Authorization"
  token-type: "JWT"
  token-role-claim: "role"
  token-issuer: "security"
  token-audience: "security-all"
  expiration-time: 7200 # 2 hours in seconds
  expiration-remember-time: 604800 # 7 days in seconds