spring:
  application:
    name: hs-web

  datasource:
    url: jdbc:mysql://localhost:3306/home_service?serverTimezone=UTC
    username: root
    password: sussql123
    hikari:
      connection-timeout: 2000
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

server:
  port: 8888

# 日志配置
logging:
  level:
    us.sushome: info
    org.springframework: info
  config: classpath:log/log4j2.xml
